# Generated by Django 4.2.7 on 2023-11-08 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimePremiumModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days",
                    models.IntegerField(
                        verbose_name=django.core.validators.MinValueValidator(1)
                    ),
                ),
            ],
            options={
                "db_table": "premium_time",
            },
        ),
    ]
