# Generated by Django 4.2.7 on 2023-11-08 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPremiumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('price', models.FloatField(blank=True, null=True, verbose_name=django.core.validators.MinValueValidator(1))),
            ],
            options={
                'db_table': 'premium_detail',
            },
        ),
        migrations.DeleteModel(
            name='TimePremiumModel',
        ),
    ]
