# Generated by Django 4.2.7 on 2023-11-08 10:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeaccount',
            name='expire_premium',
            field=models.DateTimeField(blank=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 11, 9, 10, 57, 28, 531508)), django.core.validators.MinValueValidator(datetime.datetime(2024, 2, 6, 10, 57, 28, 531515))]),
        ),
    ]
