# Generated by Django 4.2.7 on 2023-11-08 10:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_typeaccount_expire_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeaccount',
            name='expire_premium',
            field=models.DateTimeField(blank=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 11, 9, 10, 57, 42, 410976)), django.core.validators.MaxValueValidator(datetime.datetime(2024, 2, 6, 10, 57, 42, 410984))]),
        ),
    ]
