# Generated by Django 4.2.7 on 2023-11-10 11:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_typeaccount_expire_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('[A-Z][a-z]{2,24}', 'Fields must have')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('[A-Z][a-z]{2,24}', 'Fields must have')]),
        ),
        migrations.AlterField(
            model_name='typeaccount',
            name='expire_premium',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 11, 11, 13, 5, 22, 435244)), django.core.validators.MaxValueValidator(datetime.datetime(2024, 2, 8, 13, 5, 22, 435259))]),
        ),
    ]
