# Generated by Django 4.2.7 on 2023-11-11 12:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_typeaccount_expire_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('[A-Z][a-z]{2,24}', 'Fields must have only letters and start with upper')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('[A-Z][a-z]{2,24}', 'Fields must have only letters and start with upper')]),
        ),
        migrations.AlterField(
            model_name='typeaccount',
            name='expire_premium',
            field=models.DateTimeField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 11, 12, 14, 28, 25, 243465)), django.core.validators.MaxValueValidator(datetime.datetime(2024, 2, 9, 14, 28, 25, 243472))]),
        ),
    ]
